name: Auto Pull Request

on:
  push:
    branches:
      - auto-pr-branch

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Replace 'main' with your target branch name
          commit-message: 'Automated pull request'
          title: 'Automatic Pull Request'
          body: 'This is an automated pull request.'
