name: Auto Pull Request

on:
  push:
    branches:
      - auto-pr-branch  # Replace with the branch you want to trigger the action on

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-pr-branch  # Replace with the branch name where changes trigger the action
          commit-message: 'Automated pull request'
          title: 'Automatic Pull Request'
          body: 'This is an automated pull request.'

